extends Control

# This script controls the ZX Spectrum 48K emulator scene.
# It bridges the GDExtension node (ZXEmulator48K) with Godot's UI and Input systems.

@onready var emulator: ZXEmulator48K = $ZXEmulator48K
@onready var display: TextureRect = $Display
@onready var audio_player: AudioStreamPlayer = $AudioStreamPlayer
@onready var menu: CanvasLayer = $GameMenu

# List of input actions that start with "zx_" to be mapped to the emulator keyboard.
var zx_actions: Array[StringName] = []
# The audio playback object used to push raw samples to the sound card.
var audio_playback: AudioStreamGeneratorPlayback
# Buffer to accumulate mouse movement deltas before sending them to the emulator.
var mouse_accumulation: Vector2 = Vector2.ZERO

@export_group("Spectrum Arrow Mapping")
## Spectrum key to press when Arrow Up is held.
@export var key_up: String = "7"
## Spectrum key to press when Arrow Down is held.
@export var key_down: String = "6"
## Spectrum key to press when Arrow Left is held.
@export var key_left: String = "5"
## Spectrum key to press when Arrow Right is held.
@export var key_right: String = "8"

@export_group("Joystick Mapping")
## Enable Kempston Joystick signals on arrow keys / D-pad.
@export var joystick_kempston: bool = true
## Enable Sinclair Joystick signals on arrow keys / D-pad.
@export var joystick_sinclair: bool = true
## Which Sinclair Joystick to use (1 = keys 6-0, 2 = keys 1-5).
@export_range(1, 2) var sinclair_joy_num: int = 1

func _ready():
	# 1. Initialize Audio
	# We use an AudioStreamGenerator to play raw samples generated by the emulator core.
	audio_player.play()
	audio_playback = audio_player.get_stream_playback()
	
	# 2. Initialize Input Mapping
	# We look for any action in the InputMap that starts with "zx_" (e.g. "zx_space").
	# This allows us to handle input dynamically without hardcoding every key.
	for action in InputMap.get_actions():
		if action.begins_with("zx_"):
			zx_actions.append(action)
			print("Auto-mapped input action: ", action)
	
	# 3. Connect Menu signals for UI interaction
	menu.resume_requested.connect(_toggle_pause)
	menu.save_requested.connect(_save_state)
	menu.load_requested.connect(_load_state)
	menu.launcher_requested.connect(_on_launcher_requested)
	menu.reset_requested.connect(_on_reset_requested)
	menu.quit_requested.connect(_on_quit_requested)
	menu.volume_changed.connect(_change_volume)
	menu.fullscreen_requested.connect(_toggle_fullscreen)
	
	# 4. Capture Mouse for Kempston Mouse support
	# This hides the mouse and locks it to the window center for relative movement.
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
	
	# 5. Update Menu Status
	var game_name = Config.selected_game_path.get_file()
	if game_name == "": game_name = "None"
	menu.set_status("Machine: 48K | Game: " + game_name)

	
	# 6. Load ROM and the selected Game
	_load_assets()

func _load_assets():
	# 1. ROM Loading
	# The 48K model includes an internal Sinclair ROM, but we can override it if a path is provided.
	if Config.ROM_48K != "" and FileAccess.file_exists(Config.ROM_48K):
		emulator.load_rom(FileAccess.get_file_as_bytes(Config.ROM_48K))
		print("48K Custom ROM loaded: ", Config.ROM_48K)
	# 2. Game Loading
	var game_path = Config.selected_game_path
	
	if game_path == "":
		push_warning("Warning: No game selected. Starting with ROM only.")
		return
		
	if FileAccess.file_exists(game_path):
		var ext = game_path.get_extension().to_lower()
		var data = FileAccess.get_file_as_bytes(game_path)
		
		match ext:
			"tap":
				emulator.load_tape(data)
				emulator.start_tape_load()
				print("48K Tape loaded: ", game_path)
			"sna", "z80":
				emulator.load_snapshot(data)
				print("48K Snapshot loaded: ", game_path)
			"szx":
				push_warning("SZX format not supported in this build (requires rustzx-core 0.17.0+). Use .SNA or .Z80.")
			"scr":
				print("48K Screen dump preview only: ", game_path)
			_:
				push_error("Error: Unsupported file format: " + ext)
	else:
		push_error("Error: File not found: " + game_path)

func _process(_delta):
	# If the emulator is paused (menu open), we stop updating the screen and audio.
	if emulator.is_paused():
		return

	# Update the screen texture with the latest frame from the emulator.
	var tex = emulator.get_texture()
	if tex:
		display.texture = tex


	# Feed the audio buffer to prevent stuttering.
	_fill_audio_buffer()

func _fill_audio_buffer():
	if not audio_playback:
		return
	
	# Get raw samples from the emulator (interleaved Stereo floats).
	var samples = emulator.get_audio_samples()
	if samples.size() > 0:
		var frames_to_push = samples.size() / 2
		# Push each Stereo frame (Left, Right) to the AudioStreamGenerator.
		for i in range(frames_to_push):
			audio_playback.push_frame(Vector2(samples[i * 2], samples[i * 2 + 1]))

## Sends a joystick direction/fire signal to the enabled joystick interfaces.
## Uses the Joystick Mapping export variables to decide what to send.
func _send_joy(direction: String, pressed: bool):
	if joystick_kempston:
		emulator.send_joystick(direction, pressed)
	if joystick_sinclair:
		emulator.send_sinclair(sinclair_joy_num, direction, pressed)

func _toggle_pause():
	var new_state = not emulator.is_paused()
	emulator.set_paused(new_state)
	if new_state:
		menu.show()
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
	else:
		menu.hide()
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

func _get_save_path() -> String:
	var game_path = Config.selected_game_path
	if game_path == "": return "user://saves/default_48k.sna"
	
	# Create a unique filename based on the full path
	var safe_name = game_path.replace("res://", "").replace("/", "_").replace(":", "_").replace(".", "_")
	return "user://saves/" + safe_name + "_48k.sna"

func _save_state():
	# Ensure the saves directory exists
	if not DirAccess.dir_exists_absolute("user://saves"):
		DirAccess.make_dir_absolute("user://saves")
		
	# Requests a snapshot (SNA format) from the emulator core.
	var data = emulator.save_snapshot()
	if data.size() > 0:
		var path = _get_save_path()
		var file = FileAccess.open(path, FileAccess.WRITE)
		if file:
			file.store_buffer(data)
			print("Snapshot saved: ", path)
	else:
		print("Error: Received empty snapshot.")

func _load_state():
	var path = _get_save_path()
	if FileAccess.file_exists(path):
		var data = FileAccess.get_file_as_bytes(path)
		if data.size() > 0:
			emulator.load_snapshot(data)
			print("Snapshot loaded: ", path)
			_toggle_pause() # Auto-resume after loading

func _change_volume(value: float):
	audio_player.volume_db = linear_to_db(value)

func _toggle_fullscreen():
	print("Emulator: Toggling Fullscreen...")
	var current_mode = DisplayServer.window_get_mode()
	if current_mode == DisplayServer.WINDOW_MODE_FULLSCREEN or current_mode == DisplayServer.WINDOW_MODE_EXCLUSIVE_FULLSCREEN:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
		print("-> Switched to Windowed")
	else:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_EXCLUSIVE_FULLSCREEN)
		print("-> Switched to Exclusive Fullscreen")


func _input(event: InputEvent):
	# Handle Pause Menu toggle
	if event.is_action_pressed("ui_cancel"):
		_toggle_pause()
		get_viewport().set_input_as_handled()
		return

	if emulator.is_paused():
		return

	# 1. ARROW / JOYSTICK DIRECTION MAPPING
	# Sends both: keyboard key (Arrow Mapping) + joystick signals (Joystick Mapping).
	# Processed first so arrow/D-pad events are never intercepted by zx_ keyboard actions.
	if event.is_action("arrow_up"):
		var pressed = event.is_pressed()
		emulator.send_key(key_up, pressed)
		_send_joy("UP", pressed)
		get_viewport().set_input_as_handled()
		return
	if event.is_action("arrow_down"):
		var pressed = event.is_pressed()
		emulator.send_key(key_down, pressed)
		_send_joy("DOWN", pressed)
		get_viewport().set_input_as_handled()
		return
	if event.is_action("arrow_left"):
		var pressed = event.is_pressed()
		emulator.send_key(key_left, pressed)
		_send_joy("LEFT", pressed)
		get_viewport().set_input_as_handled()
		return
	if event.is_action("arrow_right"):
		var pressed = event.is_pressed()
		emulator.send_key(key_right, pressed)
		_send_joy("RIGHT", pressed)
		get_viewport().set_input_as_handled()
		return

	# 2. JOYSTICK FIRE MAPPING (zx_fire action)
	if event.is_action("zx_fire"):
		_send_joy("FIRE", event.is_pressed())
		get_viewport().set_input_as_handled()
		return

	# 3. DYNAMIC KEYBOARD MAPPING (Actions starting with 'zx_')
	for action in zx_actions:
		if event.is_action(action):
			var zx_key_name = action.substr(3)
			var pressed = event.is_pressed()
			
			emulator.send_key(zx_key_name, pressed)
				
			get_viewport().set_input_as_handled()
			return

	# 3. RAW KEYBOARD FALLBACK
	# If no specific mapping exists, we try to send the key name directly.
	if event is InputEventKey:
		var key_name = OS.get_keycode_string(event.keycode)
		emulator.send_key(key_name, event.pressed)
		return

	# 3. KEMPSTON MOUSE SUPPORT
	if event is InputEventMouseMotion:
		# We calculate how many Spectrum pixels the mouse moved.
		var display_scale = display.size.x / 256.0
		if display_scale > 0:
			mouse_accumulation += event.relative / display_scale
			
			# We only send integer deltas to the emulator.
			var delta_x = int(mouse_accumulation.x)
			var delta_y = int(mouse_accumulation.y)
			
			if delta_x != 0 or delta_y != 0:
				emulator.send_mouse_move(delta_x, delta_y)
				# Store the fraction for the next motion event.
				mouse_accumulation.x -= delta_x
				mouse_accumulation.y -= delta_y
	
	if event is InputEventMouseButton:
		# Re-capture mouse if clicking the window.
		if event.pressed and not emulator.is_paused():
			Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

		var btn = -1
		match event.button_index:
			MOUSE_BUTTON_LEFT: btn = 0
			MOUSE_BUTTON_RIGHT: btn = 1
			MOUSE_BUTTON_MIDDLE: btn = 2
		
		if btn != -1:
			emulator.send_mouse_button(btn, event.pressed)

func _on_launcher_requested():
	get_tree().change_scene_to_file("res://Scenes/Launcher/Launcher.tscn")

func _on_reset_requested():
	print("Emulator: Performing Reset...")
	_load_assets()
	_toggle_pause() # Auto-resume

func _on_quit_requested():
	get_tree().quit()
